### ISSUE TITLE
Crawling stuck after a few URLs

### ISSUE THREAD

**Issue by antHeater** [ninoseki/miteru#127] opened 2020-01-14 14:40 UTC
Since update to version 0.13.0 the feed crawling gets stuck after few URLs, no errors, I tried many options combinations with same output.

This is the latest try, manually interrupted because stuck there for hours:

`$ /usr/local/bin/miteru execute --threads=12 --directory-traveling --size=4000 --auto-download --download-to=/opt/miteru/`
```
Loaded 9610 URLs to crawl. (crawling in 12 threads)
http://103.112.226.142/Mozi.m: It doesn't contain a phishing kit.
http://103.112.226.142: It doesn't contain a phishing kit.
http://103.30.183.173: It doesn't contain a phishing kit.
http://103.30.183.173/adm/sites: It doesn't contain a phishing kit.
http://103.30.183.173/adm: It doesn't contain a phishing kit.
http://103.91.90.221: It doesn't contain a phishing kit.
http://104.131.148.172/1kfhr7: It doesn't contain a phishing kit.
http://104.131.148.172/1kfhr7/multifunctional-box: It doesn't contain a phishing kit.
http://104.131.148.172: It doesn't contain a phishing kit.
http://104.248.26.90: It doesn't contain a phishing kit.
http://103.91.90.221/AdminPanel: It doesn't contain a phishing kit.
http://104.248.26.90/wp-admin/127016282754576: It doesn't contain a phishing kit.
http://104.248.26.90/wp-admin/127016282754576/ixee5102uofn: It doesn't contain a phishing kit.
http://103.30.183.173/adm/sites/zn4uqjzca: It doesn't contain a phishing kit.
http://104.248.26.90/wp-admin/127016282754576/ixee5102uofn/8yq-00923-71189530-n6iw8-ptmmjll: It doesn't contain a phishing kit.
http://104.131.148.172/1kfhr7/multifunctional-box/close-4xol48ieqx-7dupxos475y8: It doesn't contain a phishing kit.
http://103.91.90.221/AdminPanel/Reporting: It doesn't contain a phishing kit.
http://104.131.148.172/1kfhr7/multifunctional-box/close-4xol48ieqx-7dupxos475y8/018438913656-Upg2Is7: It doesn't contain a phishing kit.
http://104.248.26.90/wp-admin: It doesn't contain a phishing kit.
http://106.12.111.189: It doesn't contain a phishing kit.
http://108.171.179.117: It doesn't contain a phishing kit.
http://108.171.179.117/qbshelpdesk: It doesn't contain a phishing kit.
http://106.12.111.189/wr0pezn/sites/s0kgm6: It doesn't contain a phishing kit.
http://108.171.179.117/qbshelpdesk/55br0-tqr-155: It doesn't contain a phishing kit.
http://106.12.111.189/wr0pezn: It doesn't contain a phishing kit.
^CTraceback (most recent call last):
	19: from /usr/local/bin/miteru:23:in `<main>'
	18: from /usr/local/bin/miteru:23:in `load'
	17: from /var/lib/gems/2.5.0/gems/miteru-0.13.0/exe/miteru:8:in `<top (required)>'
	16: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	15: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	14: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	12: from /var/lib/gems/2.5.0/gems/miteru-0.13.0/lib/miteru/cli.rb:30:in `execute'
	11: from /var/lib/gems/2.5.0/gems/miteru-0.13.0/lib/miteru/crawler.rb:53:in `execute'
	10: from /var/lib/gems/2.5.0/gems/miteru-0.13.0/lib/miteru/crawler.rb:30:in `execute'
	 9: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:227:in `each'
	 8: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:275:in `map'
	 7: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:353:in `work_in_threads'
	 6: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:204:in `in_threads'
	 5: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:204:in `handle_interrupt'
	 4: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:211:in `block in in_threads'
	 3: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:211:in `handle_interrupt'
	 2: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:212:in `block (2 levels) in in_threads'
	 1: from /var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:212:in `map'
/var/lib/gems/2.5.0/gems/parallel-1.19.1/lib/parallel.rb:212:in `value': Interrupt
```

System info:
Ubuntu 18.04.3 LTS
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by ninoseki** [comment] 2020-01-15 08:55
I cannot figure out the root cause of the problem in the log.
But Mietru isn't tested under Ruby 2.5.  So upgrading to Ruby 2.6 might solve the issue.

**Comment by antHeater** [comment] 2020-01-15 10:56
Ruby 2.6 [ruby 2.6.5p114 (2019-10-01 revision 67812)] didn't solve the issue. 
Any suggestion how to debug what's going wrong during the feed crawling?
thanks

**Comment by ninoseki** [comment] 2020-09-22 08:26
There is no similar claim for a long time. So I close this issue.

**Closed by ninoseki** 2020-09-22 08:26 UTC
